# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

TEST_DEVICE="iPhone 13"
TEST_IOS_VERSION="15.0"

PROJECT_SCHEME="iOS Test"

default_platform(:ios)

platform :ios do
  desc "Test Project"
  lane :test do
    scan(
      scheme: PROJECT_SCHEME,
      clean: false,
      device: TEST_DEVICE,
      code_coverage: true
    )
  end

desc "Check code coverage"
  lane :check_coverage do
    danger(
      danger_id: 'coverage-threshold',
      dangerfile: 'DangerCoveragefile',
      github_api_token: ENV['DANGER_GITHUB_API_TOKEN'],
      verbose: true
    )
  end

 ##### Lane to generate HTML unit test coverage on local #####
  desc("Generating slather test coverage HTML report")
  lane :slather_html_report do
    slather(
      scheme: PROJECT_SCHEME,
      output_directory: "fastlane/slather_output",
      html: true,
      ignore: [
        "iOS\ Test/Utilities/**",
        "iOS\ Test/ResponseModels/**",
        "vendor/*",
	"UIImage**",
	"UIView**",
	"Operations.swift",
	"UITableView**",
        "**Builder.swift",
	"**Error.swift",
        "**Factory.swift",
        "**Resource.swift",
        "**Response.swift",
        "**Controller.swift",
        "**Cell.swift",
        "**Event.swift",
        "**Router.swift",
        "**FlowLayout.swift",
        "**Channel.swift",
        "**View.swift",
        "**Communication.swift"
      ]
    )
  end
end
