name: Build & Test

on:
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11]
        xcode: ['13.1']
    runs-on: ${{ matrix.os }}
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
      DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 100
    - name: Install XCPretty
      run: gem install xcpretty

    - name: Install lcov
      run: brew install lcov
      
    - uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.SSH_GITHUB_ACTIONS }}
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Check spm cache for dependencies
      uses: actions/cache@v2
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
    - name: Build and test
      run: bundle exec fastlane test generate_xcodebuild_log:true

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: "37d6ab8b-69f3-4625-84c9-d102a96856ef"
        files: cobertura.xml
        directory: fastlane/slather_output/
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)

    - name: check coverage
      run: bundle exec fastlane check_coverage


