name: Build & Test

on:
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11]
        xcode: ['13.1']
    runs-on: ${{ matrix.os }}
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
      DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 100
    - name: Install XCPretty
      run: gem install xcpretty
      run: brew install lcov
      
    - uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.SSH_GITHUB_ACTIONS }}
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Check spm cache for dependencies
      uses: actions/cache@v2
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
    - name: Build and test
      run: bundle exec fastlane test generate_xcodebuild_log:true

    - name: generate lcov report
      run: bundle exec fastlane generate_lcove_report

    - name: Check coverage
      run: bundle exec fastlane check_coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@1.1.3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}


