name: Build & Test

on:
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11]
        xcode: ['13.1']
    runs-on: ${{ matrix.os }}
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Install XCPretty
      run: gem install xcpretty
    - uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.SSH_GITHUB_ACTIONS }}
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.5
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Build and test
      run: bundle exec fastlane test
